version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd node
      - npm install
      - cd ../react
      - npm install
  build:
    commands:
      - cd react
      - npm run build
artifacts:
  files:
    - react/build/**/*
