version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
      - cd technical-dictionary-ui
      - npm install
  build:
    commands:
      - cd technical-dictionary-ui
      - npm run build
      - cd ..
      - npm run build
artifacts:
  files:
    - technical-dictionary-ui/build/**/*
